const types = {    
    GLOBAL_STATUS_NONUSER_TOKEN : 'GLOBAL_STATUS_NONUSER_TOKEN',
    GLOBAL_STATUS_USER_TOKEN : 'GLOBAL_STATUS_USER_TOKEN',
    GLOBAL_STATUS_DRAWER_OPEN : 'GLOBAL_STATUS_DRAWER_OPEN',
    GLOBAL_STATUS_TOGGLE_CATEGORY : 'GLOBAL_STATUS_TOGGLE_CATEGORY',
    GLOBAL_STATUS_TOGGLE_PRODUCT : 'GLOBAL_STATUS_TOGGLE_PRODUCT',
    GLOBAL_STATUS_TOGGLE_NOTICE_DETAIL : 'GLOBAL_STATUS_TOGGLE_NOTICE_DETAIL',
    GLOBAL_STATUS_TOGGLE_BANNER_DETAIL : 'GLOBAL_STATUS_TOGGLE_BANNER_DETAIL',
    GLOBAL_STATUS_CHOICE_CATEGORY_ARRAY : 'GLOBAL_STATUS_CHOICE_CATEGORY_ARRAY',
    GLOBAL_STATUS_CHOICE_PRODUCT_ARRAY : 'GLOBAL_STATUS_CHOICE_PRODUCT_ARRAY',
    GLOBAL_STATUS_USER_CART : 'GLOBAL_STATUS_USER_CART',
    GLOBAL_STATUS_USER_ZZIM : 'GLOBAL_STATUS_USER_ZZIM',
    GLOBAL_STATUS_MY_ZZIM_LIST : 'GLOBAL_STATUS_MY_ZZIM_LIST',
    GLOBAL_STATUS_USER_ORDERING : 'GLOBAL_STATUS_USER_ORDERING',
    GLOBAL_STATUS_USER_POINT : 'GLOBAL_STATUS_USER_POINT'
}

export default types;
